### ISSUE TITLE
No tag 'latest' for the Azkube image on DockerHub

### ISSUE THREAD

**Issue by theobolo** [colemickens/azkube#1]
Hi Cole,

I've noticed that the only image that you have provided on Dockerhub is "v0.0.1", the tag "latest" is not available and is not working as you expect in your README on the repo.

I dont want to push a latest tagged image, i'll let do it :)

Cheers;

**Comment by colemickens** [comment]
I went ahead and pushed `v0.0.2` and `latest` today and have updated the Makefile so that it will tag `latest` whenever I do a push to a tagged release. Thanks for the report.

**Comment by theobolo** [comment]
You'r welcome, btw thanks for that 0.0.2 i'll test that today ;)
