### ISSUE TITLE
kube-up cluster validation fails

### ISSUE THREAD

**Issue by vtuson** [colemickens/azkube#10]
When running azkue from kube-up.sh I always get 
INFO[0273] Validating Kubernetes cluster.
WARN[0274] Failed to validate components: Get https://kube-20160715-132738.westus.cloudapp.azure.com:6443/api/v1/componentstatuses: dial tcp 13.91.93.132:6443: getsockopt: connection refused

I can ssh to the master node, and I can see that cloud-init failes to run, when executed manually you get:
sudo /usr/bin/coreos-cloudinit --oem=azure
2016/07/15 12:36:14 Checking availability of "waagent"
2016/07/15 12:36:14 Fetching user-data from datasource of type "waagent"
2016/07/15 12:36:14 Attempting to read from "/var/lib/waagent/CustomData"
2016/07/15 12:36:14 line 1: error: must be "#cloud-config" or begin with "#!"
2016/07/15 12:36:14 Fetching meta-data from datasource of type "waagent"
2016/07/15 12:36:14 Attempting to read from "/var/lib/waagent/SharedConfig.xml"
Failed to parse user-data: Unrecognized user-data format
Continuing...
2016/07/15 12:36:14 Merging cloud-config from meta-data and user-data
2016/07/15 12:36:14 Updated /etc/environment
2016/07/15 12:36:14 Ensuring runtime unit file "etcd.service" is unmasked
2016/07/15 12:36:14 Ensuring runtime unit file "etcd2.service" is unmasked
2016/07/15 12:36:14 Ensuring runtime unit file "fleet.service" is unmasked
2016/07/15 12:36:14 Ensuring runtime unit file "locksmithd.service" is unmasked

Any thoughts on what could go wrong?

**Comment by theobolo** [comment]
@vtuson Hi, It's about a problem with the new Beta version of CoreOS.
Azkube is using the Azure WaAgent to configure the oem-cloudinit.service inside CoreOS at startup, please take a look at the issue related: 

https://github.com/Azure/WALinuxAgent/issues/330

For the moment there is something wrong during the cloud-init initialization because of that.

Azkube will be updated soon to launch the stable version of CoreOS and not the Beta.

**Comment by vtuson** [comment]
looking into it a bit more... could it be the problem that this file is with base64 encoding rather than plain? 
/var/lib/waagent/CustomData

I have decoded it , replace it and restart the service
sudo systemctl start oem-cloudinit.service

and the service now seems happy
sudo systemctl status oem-cloudinit.service
● oem-cloudinit.service - Cloudinit from Azure metadata
   Loaded: loaded (/run/systemd/system/oem-cloudinit.service; static; vendor preset: disabled)
   Active: inactive (dead)

Jul 15 12:57:22 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:22 Ensuring runtime unit
Jul 15 12:57:23 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:23 Calling unit command
Jul 15 12:57:23 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:23 Result of "start" on
Jul 15 12:57:23 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:23 Calling unit command
Jul 15 12:57:33 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:33 Result of "start" on
Jul 15 12:57:33 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:33 Calling unit command
Jul 15 12:57:33 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:33 Result of "start" on
Jul 15 12:57:33 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:33 Calling unit command
Jul 15 12:57:46 kube-20160715-132738-vm-master coreos-cloudinit[1533]: 2016/07/15 12:57:46 Result of "start" on
Jul 15 12:57:46 kube-20160715-132738-vm-master systemd[1]: Started Cloudinit from Azure metadata.

**Comment by theobolo** [comment]
@vtuson Thanks for that ! I let Cole answer ;)

**Comment by colemickens** [comment]
I've pushed a commit to master to fix this issue. I've also published the updated container on Docker Hub under the 'v0.0.5' and 'v0.0.6' tags so that Kube 1.3 users benefit from this fix.

Please try `docker pull docker.io/colemickens/azkube:v0.0.5` and then try the process again. It should work now.

**Comment by colemickens** [comment]
Closing this for now as I believe it's resolved. Feel free to reopen or open a new issue if you continue to experience problems.
