### ISSUE TITLE
[Azkube v.0.0.2] Skydns and kube-system namespace not working.

### ISSUE THREAD

**Issue by theobolo** [colemickens/azkube#2]
Hi,

So today i've tried the new Azkube version with your guide.

After some scripts modifying i was finally able to use util.sh and kube-up.sh. 
I'll open an other issue for that little bugs.

Btw, the cluster is working except the master-addons like Skydns, the kube-system namespace is missing also.

**Comment by colemickens** [comment]
Have you tried deploying the addons?

**Comment by theobolo** [comment]
How ?

**Comment by colemickens** [comment]
Working on getting you instructions for this along with a readme or something.

**Comment by theobolo** [comment]
I saw that you'r working on it too so i close it.
