### ISSUE TITLE
[Question] Connect to nodes

### ISSUE THREAD

**Issue by otaviosoares** [colemickens/azkube#7]
Is it possible to connect to nodes via SSH? I can ping the local IP's of the vms of scale set from the master but wasn't able to connect to them.

The reason I need to connect is to install the dependencies to use azure file storage.

Thank you

**Comment by colemickens** [comment]
In the deployment directory, there is the `util.sh`. You should be able to call `util.sh copykey` (which will copy the SSH private key to the master) and then use `ssh -i kube_rsa 10.0.0.4` (or `10.0.0.x`) to access one of the nodes.

Can you give me more details? How are you unable to connect?

**Comment by otaviosoares** [comment]
Thank you @colemickens 

I just didn't know how to get the key. Now it's all fine.
